version: "3.7"

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    env_file:
      - ./env/general.env
    volumes:
      - ./data:/usr/share/nginx/html
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/logs:/var/log/nginx/
    working_dir: /usr/share/nginx/html
    depends_on:
      - php7.4-fpm
    networks:
      - internal

  php7.4-fpm:
    build:
      context: ./php
    env_file:
      - ./env/general.env
    volumes:
      - ./data:/usr/share/nginx/html
      - ./php/logs:/var/log/php/
      - ./php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /usr/share/nginx/html
    depends_on:
      - mailhog
    networks:
      - internal

  mariadb:
    image: bitnami/mariadb
    restart: always
    env_file:
      - ./env/general.env
      - ./env/mariadb.env
    volumes:
      - ./mariadb:/bitnami/mariadb
      - ./mariadb/conf/my_custom.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
      - ./mariadb/logs:/opt/bitnami/mariadb/logs
    networks:
      - internal

  adminer:
    build:
      context: ./adminer
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./env/general.env
      - ./env/adminer.env
    depends_on:
      - mariadb
    networks:
      - internal

  mailhog:
    build:
      context: ./mailhog
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
    env_file:
      - ./env/general.env
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
